### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by francisdb** [ruippeixotog/think-bayes-scala#8]
I see no license mentioned in the readme. Your build file mentions MIT but wanted to be sure this is correct.

**Comment by ruippeixotog** [comment]
Hi! Yes, this is MIT licensed. It seems that I forgot to add the LICENSE file and the copyright notice on the README when I created this project, I'll add them later.

**Comment by francisdb** [comment]
One more question, would your lib be able to handle these kinds of networks?

https://github.com/danielkorzekwa/bayes-scala/blob/master/doc/dsl/student_bayesian_network/student_bayesian_network.md

**Comment by ruippeixotog** [comment]
You could easily model that network in think-bayes-scala, even though the API and the conceptual model behind the two libraries are a bit different.

While the example you gave is clearly mutable and variables store references to the others, those dependencies are not encoded here. Instead, every discrete distribution is an immutable `Pmf`, which you can manipulate as it was a Scala collection. You can combine `Pmf`s just like in the example and you can still end up with all the results presented there.
